Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -18,4 +18,15 @@ jobs:
         with:
           version: ${{ matrix.version }}
           pre: 1
-
+      - name: test docs build
+        if: ${{ github.event_name == "pull_request" && matrix.version == "3.9" && matrix.os == "ubuntu" }}
+        run: |
+          nbdev_docs
+          if [ -f "_docs/index.html" ]; then
+            echo "docs built successfully."
+          else
+            echo "index page not found in rendered docs."
+            ls -la
+            ls -la _docs
+            exit 1
+          fi
