Update test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -22,8 +22,11 @@ jobs:
         run: |
           nbdev_docs
           if [ -f "_docs/index.html" ]; then
-            echo "docs built successfully.";
+            echo "docs built successfully."
           else
-            exit 1;
+            echo "index page not found in rendered docs."
+            ls -la
+            ls -la _docs
+            exit 1
           fi
 
